### ISSUE TITLE
Problème Git pour cloner le repo Presentation

### ISSUE THREAD

**Issue by LaurentLienhard** [FrPSUG/Presentations#27]
# Problème Git pour cloner le repos Presentation

J'ai fait un fork du repo et quand j'essai de le cloner sur mon PC j'ai une erreur : 
```
Fatal: unable to checkout working tree
warning: Cone succeeded but chekout failed
You can inspect what was checked out with 'git status'
an retry the checkout with 'git checkout -f HEAD'
```

j'ouvre donc un Git dans le répertoire cloner et je fais un git status et je recois
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .github/
        README.md
        presentations/

```

je fais un git checkout -f HEAD : 
```
$ git checkout -f HEAD
error: unable to create file presentations/20180418-Gestion-d_une-Infrastructure-VMware-avec-PowerCLI_(Jérôme_Bezet-Torres)/02 Démonstrations/04 Démonstration WPF/StormShield/assembly/MahApps.Metro.IconPacks.FontAwesome.dll: Filename too long
error: unable to create file presentations/20180418-Gestion-d_une-Infrastructure-VMware-avec-PowerCLI_(Jérôme_Bezet-Torres)/02 Démonstrations/04 Démonstration WPF/StormShield/assembly/MahApps.Metro.IconPacks.MaterialLight.dll: Filename too long
Checking out files: 100% (310/310), done.
Your branch is up to date with 'origin/master'.

```
a priori des noms de fichier trop long

**Comment by copdips** [comment]
j'ai pas eu de pb pdt le git clone.
windows v10
git v2.21.0

quel est le chemin racine du repo ?

**Comment by LaurentLienhard** [comment]
Effectivement je pense que le problème vient de chez moi. Quand je clone vers c:\temp pas de souci mais si je clone dans mon répertoire dans dropbox erreur
![image](https://user-images.githubusercontent.com/22775196/57530711-189fcf00-7338-11e9-8735-047a6dc59976.png)
